// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rydfutjgigsytwaqmvax.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ5ZGZ1dGpnaWdzeXR3YXFtdmF4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2OTcwNDEsImV4cCI6MjA2ODI3MzA0MX0.j-Qsm6d6tKV_5dEIzlrY_DNZ8NjUhFAjIAaFJuycO0k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});